### PR TITLE
fix: update regex resourceName match logic

### LINKED ISSUE #1418: Events which created by AutoEvent contains the reading didn't set on device AutoEvent
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-service

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/8a22ffe3ee580c257e50e40c2b53eff48da465fe/docker-compose-no-secty.yml#L27)
2. Verify the events of `Random-UnsignedInteger-Device` which pushing by auto event

```
GET  localhost:59880/api/v2/event/device/name/Random-UnsignedInteger-Device

{
    "apiVersion": "v2",
    "statusCode": 200,
    "totalCount": 28,
    "events": [
        {
            "apiVersion": "v2",
            "id": "8f8f2746-d892-408e-8eff-42546b9a10a8",
            "deviceName": "Random-UnsignedInteger-Device",
            "profileName": "Random-UnsignedInteger-Device",
            "sourceName": "Uint16",
            "origin": 1681191249346359994,
            "readings": [
                {
                    "id": "d5c3b949-8778-4436-a15b-320827a2cfc0",
                    "origin": 1681191249346359994,
                    "deviceName": "Random-UnsignedInteger-Device",
                    "resourceName": "Uint16Array",
                    "profileName": "Random-UnsignedInteger-Device",
                    "valueType": "Uint16Array",
                    "value": "[24214, 10860, 9406, 54914, 7435]"
                },
                {
                    "id": "308af7f6-0a3d-4d9e-8cff-20ce698db4b9",
                    "origin": 1681191249346359994,
                    "deviceName": "Random-UnsignedInteger-Device",
                    "resourceName": "Uint16",
                    "profileName": "Random-UnsignedInteger-Device",
                    "valueType": "Uint16",
                    "value": "39176"
                }
            ]
        },
...
}
```

## 🔥 Exception or Error
[Default auto event setting](https://github.com/edgexfoundry/device-virtual-go/blob/9393cb199918d0b51a604a638f19df0ef5e84a0a/cmd/res/devices/devices.yaml#L47-L60) didn't contain resource Uint16Array, but got the `Uint16Array reading` in the event

## 🌍  Your Environment
**Deployment Environment:** Ubuntu22 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by hahattan**
Use `CompilePOSIX` and `FindString` and check that the string found is the entire resource name

closes #1418

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Build and Run `device-virtual` from this branch
2. Verify autoevent `Uint16` returns only 1 reading `Uint16`

### CODE REVIEW

**Comment by iain-anderson** [comment]
What are the performance implications of the regex matching? Would it be better to check for an exact match first and only if this fails would we go on to compile the regex and look for matches?

File: internal/application/command.go [hunk 1]
```diff
@@ -141,7 +142,12 @@ func readDeviceResource(device models.Device, resourceName string, attributes st
 }
 
 func readDeviceResourcesRegex(device models.Device, regexResourceName string, attributes string, dic *di.Container) (res *dtos.Event, edgexErr errors.EdgeX) {
-	deviceResources, ok := cache.Profiles().DeviceResourcesByRegex(device.ProfileName, regexResourceName)
+	re, err := regexp.CompilePOSIX(regexResourceName)
+	if err != nil {
+		return res, errors.NewCommonEdgeX(errors.KindContractInvalid, "failed to CompilePOSIX resource name", err)
```
Comment (lenny-intel) [inline internal/application/command.go:147]: Why is `res` used for the event, why not event?

File: internal/application/command.go [hunk 2]
```diff
@@ -141,7 +142,12 @@ func readDeviceResource(device models.Device, resourceName string, attributes st
 }
 
 func readDeviceResourcesRegex(device models.Device, regexResourceName string, attributes string, dic *di.Container) (res *dtos.Event, edgexErr errors.EdgeX) {
-	deviceResources, ok := cache.Profiles().DeviceResourcesByRegex(device.ProfileName, regexResourceName)
+	re, err := regexp.CompilePOSIX(regexResourceName)
```
Comment (lenny-intel) [inline internal/application/command.go:145]:
```suggestion
	regex , err := regexp.CompilePOSIX(regexResourceName)
```

File: internal/cache/profiles_test.go [hunk 3]
```diff
@@ -199,18 +202,22 @@ func Test_profileCache_DeviceResourcesByRegex(t *testing.T) {
...
+		{"valid - resources found by regex pattern", TestProfile, "testResource.*", 2, true},
+		{"Valid -  resources not found by regex pattern", TestProfile, "^resource.*", 0, true},
+		{"invalid - profile not found", "nil", "%2E%2B-resource", 0, false},
 	}
 	for _, tt := range tests {
 		t.Run(tt.name, func(t *testing.T) {
-			res, ok := pc.DeviceResourcesByRegex(tt.profileName, tt.regexResourceName)
-			assert.Equal(t, res, tt.deviceResources, "DeviceResource returns wrong deviceResource")
-			assert.Equal(t, ok, tt.expected, "DeviceResource returns opposite result")
+			re, err := regexp.CompilePOSIX(tt.regexResourceName)
```
Comment (lenny-intel) [inline internal/cache/profiles_test.go:215]:
```suggestion
			regex , err := regexp.CompilePOSIX(tt.regexResourceName)
```

**Review by lenny-intel — CHANGES_REQUESTED** [review]

File: internal/application/command.go (hunk 1 above)
Comment (hahattan) [reply internal/application/command.go]: added edf083397e33d0cd5580647af7401469445553ce to refactor this

**Comment by hahattan** [comment]
> What are the performance implications of the regex matching? Would it be better to check for an exact match first and only if this fails would we go on to compile the regex and look for matches?

Did a simple benchmark and yes the performance is better if we're matching against non-regex-string, updated.
(not much difference if matching against regex string)

**Review by lenny-intel — APPROVED** [review]
LGTM

**Review by cloudxxx8 — APPROVED** [review]
LGTM
