### PR TITLE
fix: Remove device profile from the cache properly

### LINKED ISSUE #1599: Stale Device Profile might be kept in cache
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device sdk

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]
If users modify the profileName from a Device, and remove the Profile from core-metadata.  The old profile would still be in the Device SDK cache.
The issue will happen when the user create another Profile with the same name, and the Device Service will still use the stale Profile in the cache.

Device SDK should handle the Profile deletion system event to remove the profile from cache properly.
This logic can be removed after the Profile deletion system event is implemented.
https://github.com/edgexfoundry/device-sdk-go/blob/119f0d3508c34fcb2e951725a389e94afb6ed809/internal/application/callback.go#L177-L187

### PR DESCRIPTION
**Pull request by jinlinGuan**
close #1599

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

File: internal/application/callback.go [hunk 1]
```diff
@@ -53,6 +53,19 @@ func UpdateProfile(profileRequest requests.DeviceProfileRequest, dic *di.Contain
...
+func DeleteProfile(profileName string, dic *di.Container) errors.EdgeX {
+	lc := bootstrapContainer.LoggingClientFrom(dic.Get)
+	if cache.CheckProfileNotUsed(profileName) {
+		err := cache.Profiles().RemoveByName(profileName)
+		if err != nil {
+			errMsg := fmt.Sprintf("failed to remove device profile %s", profileName)
+			return errors.NewCommonEdgeX(errors.KindServerError, errMsg, err)
+		}
+	}
+	lc.Debugf("profile %s is removed from cache", profileName)
```
Comment (cloudxxx8) [inline internal/application/callback.go:65]: if `cache.CheckProfileNotUsed` returns false, print a warning "received Profile Deletion System Event for %s(profileName), but the profile is still used by some devices"

Also, don't print `lc.Debugf("profile %s is removed from cache", profileName)` if `cache.CheckProfileNotUsed` returns false

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

File: internal/application/callback.go [hunk 2]
```diff
@@ -53,6 +53,22 @@ func UpdateProfile(profileRequest requests.DeviceProfileRequest, dic *di.Contain
...
+	lc := bootstrapContainer.LoggingClientFrom(dic.Get)
+	if cache.CheckProfileNotUsed(profileName) {
+		err := cache.Profiles().RemoveByName(profileName)
+		if err != nil {
+			errMsg := fmt.Sprintf("failed to remove device profile %s", profileName)
+			return errors.NewCommonEdgeX(errors.KindServerError, errMsg, err)
+		}
+		lc.Debugf("profile %s is removed from cache", profileName)
+	} else {
+		lc.Warnf("received Profile Deletion System Event for %s(profileName), but the profile is still used by some devices", profileName)
```
Comment (cloudxxx8) [inline internal/application/callback.go:66]:
```suggestion
		lc.Warnf("received Profile Deletion System Event for %s, but the profile is still used by some devices", profileName)
```

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM
