### PR TITLE
fix: Update ProfileCache when adding or updating the Provision Watcher

### LINKED ISSUE #1053: Device profile not loaded in cache if device for profile doesn't exist
# 🐞 Bug Report

### Description and Minimal Reproduction
Run migrated LLRP device service, which uses provision watcher and no static devices
https://github.com/marcpfuller/device-rfid-llrp-go

*note in logs that provision watcher failed to add due to profile not found in cache

you can see in the code link below that it is loaded by device
https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/cache/init.go#L37-L45

Here shows that the provision watcher is trying to get to the profile via the cache
https://github.com/edgexfoundry/device-sdk-go/blob/main/pkg/service/managedwatchers.go#L31

## 🔥 Exception or Error
<pre><code>
level=DEBUG ts=2021-11-04T21:43:33.10203Z app=edgex-device-rfid-llrp source=driver.go:720 msg="2 provision watcher files found"
level=DEBUG ts=2021-11-04T21:43:33.1020664Z app=edgex-device-rfid-llrp source=driver.go:725 msg="processing res/provision_watchers/impinj.provision.watcher.json"
level=ERROR ts=2021-11-04T21:43:33.1023475Z app=edgex-device-rfid-llrp source=managedwatchers.go:61 msg="failed to find ProvisionWatcher llrp-impinj-provision-watcher in cache"
level=INFO ts=2021-11-04T21:43:33.1024189Z app=edgex-device-rfid-llrp source=driver.go:750 msg="Adding provision watcher:llrp-impinj-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1024522Z app=edgex-device-rfid-llrp source=managedwatchers.go:34 msg="device profile LLRP-Impinj-Profile doesn't exist for provision watcher llrp-impinj-provision-watcher"
level=DEBUG ts=2021-11-04T21:43:33.1024818Z app=edgex-device-rfid-llrp source=driver.go:725 msg="processing res/provision_watchers/llrp.provision.watcher.json"
level=ERROR ts=2021-11-04T21:43:33.10262Z app=edgex-device-rfid-llrp source=managedwatchers.go:61 msg="failed to find ProvisionWatcher llrp-provision-watcher in cache"
level=INFO ts=2021-11-04T21:43:33.102658Z app=edgex-device-rfid-llrp source=driver.go:750 msg="Adding provision watcher:llrp-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1026816Z app=edgex-device-rfid-llrp source=managedwatchers.go:34 msg="device profile LLRP-Device-Profile doesn't exist for provision watcher llrp-provision-watcher"
level=ERROR ts=2021-11-04T21:43:33.1027245Z app=edgex-device-rfid-llrp source=driver.go:816 error="error adding provision watcher llrp-impinj-provision-watcher: device profile LLRP-Impinj-Profile doesn't exist for provision watcher llrp-impinj-provision-watcher; error adding provision watcher llrp-provision-watcher: device profile LLRP-Device-Profile doesn't exist for provision watcher llrp-provision-watcher" msg="Error adding provision watchers. Newly discovered devices may fail to register with EdgeX."
level=DEBUG ts=2021-11-04T21:43:33.1028128Z app=edgex-device-rfid-llrp source=discover.go:120 msg="total estimated network probes: 508, async limit: 508, probe timeout: 2s, total estimated time: 2s"
</code></pre>

## 🌍  Your Environment
**EdgeX Version:**
Ireland and Jakarta WIP

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by weichou1229**
Update ProfileCache when adding or updating the Provision Watcher to stay consistent with core metadata

Closes #1053

Signed-off-by: bruce <weichou1229@gmail.com>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) **not impact the unit test**
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) **not impact the doc**
  <link to docs PR>

## Testing Instructions

1. Run core services
2. Run the device-rfid-llrp-go based on the branch https://github.com/marcpfuller/device-rfid-llrp-go
3. check whether the provision watcher is added

### CODE REVIEW

**Comment by weichou1229** [comment]
@marcpfuller 
Could you help verify the PR?

**Review by cloudxxx8 — APPROVED** [review]
LGTM

File: pkg/service/managedwatchers.go [hunk 1]
```diff
@@ -30,9 +30,12 @@ func (s *DeviceService) AddProvisionWatcher(watcher models.ProvisionWatcher) (st
 
 	_, ok := cache.Profiles().ForName(watcher.ProfileName)
 	if !ok {
-		errMsg := fmt.Sprintf("device profile %s doesn't exist for provision watcher %s", watcher.ProfileName, watcher.Name)
-		s.LoggingClient.Error(errMsg)
-		return "", errors.NewCommonEdgeX(errors.KindEntityDoesNotExist, errMsg, nil)
+		_, err := s.edgexClients.DeviceProfileClient.DeviceProfileByName(context.Background(), watcher.ProfileName)
```
Comment (lenny-intel) [inline pkg/service/managedwatchers.go:33]: Why not put the profile in the cache here at this point? Will there not be other issues accessing the profile when the ProvisionWatcher detects a new device???

Or better yet, just put it in the cache during the start-up code that loads and pushes/pulls the profile to/from Core Metadata, like it was in V1. https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/provision/profiles.go#L83-L90

This enables hybrid mode (command line with Core Metadata in docker) to work smoother for development purposes. It also reduces the complexities (amount of code changes in the PR)

**Review by lenny-intel — CHANGES_REQUESTED** [review]

File: pkg/service/managedwatchers.go (hunk 1 above)
Comment (weichou1229) [reply pkg/service/managedwatchers.go:33]: > Why not put the profile in the cache here at this point? Will there not be other issues accessing the profile when the ProvisionWatcher detects a new device???

I thought it just a convenient func to add the ProvisionWatcher to core-metadata like the 
 AddDevice func of manageddevices.go. 
https://github.com/edgexfoundry/device-sdk-go/blob/main/pkg/service/manageddevices.go#L27
The core-metadata will invoke the device service callback after adding the ProvisionWatcher.

> Or better yet, just put it in the cache during the start-up code that loads and pushes/pulls the profile to/from Core Metadata, like it was in V1.

It should be an enhancement to let the user predefine the ProvisionWatcher.

Comment (lenny-intel) [reply pkg/service/managedwatchers.go:33]: @weichou1229, with your approach we will have grown to have 4 locations of code that are loading profiles from Core Metadata (3 of which are ignoring the returned profile):
1. The one above that you have added.
2. Here once the devices have been loaded: https://github.com/edgexfoundry/device-sdk-go/blob/5b7ab9a3ff9866f95cdc84e39a450aa5b3c9b9ea/internal/cache/init.go#L39
3. Here when a device is loaded: https://github.com/edgexfoundry/device-sdk-go/blob/5b7ab9a3ff9866f95cdc84e39a450aa5b3c9b9ea/pkg/service/manageddevices.go#L34
4. Here on startup: https://github.com/edgexfoundry/device-sdk-go/blob/main/internal/provision/profiles.go#L83
5. If the 4th one would simply put the profiles into cache, instead of ignoring the response the other 3 are not needed.

Comment (cloudxxx8) [reply pkg/service/managedwatchers.go:33]: @lenny-intel you are right.  I didn't notice that.  we should add it to cache whenever loading from core-metadata to prevent additional query.

Comment (weichou1229) [reply pkg/service/managedwatchers.go:33]: Added code to put the profiles into the cache when loading the predefined profile.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Review by lenny-intel — APPROVED** [review]
LGTM
