### PR TITLE
fix: Add core-metadata dependency check

### LINKED ISSUE #1677: Add core-metadata dependency check in device-sdk-go init
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device services

### Is this a regression?

 Yes, the previous version in which this bug was not present was: v3.1

### Description and Minimal Reproduction [**REQUIRED**]
After resolving https://github.com/edgexfoundry/go-mod-bootstrap/issues/804 , device service won't check the core-metadata client dependency by timer.

We removed this logic from SDK in v3.  It was:
https://github.com/edgexfoundry/device-sdk-go/blob/7058336d413b965c65ab77fbf704600e65827876/internal/clients/init.go#L117-L135

We should add the logic back in
https://github.com/edgexfoundry/device-sdk-go/blob/6b365886e86a8ee1260e36154773f2301536abcf/pkg/service/init.go#L55-L64

## 🔥 Exception or Error
service stops if core-metadata is not availabe during bootstrap

### PR DESCRIPTION
**Pull request by jinlinGuan**
close #1677

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

### CODE REVIEW

File: pkg/service/init.go [hunk 1]
```diff
@@ -127,7 +133,41 @@ func (b *Bootstrap) BootstrapHandler(ctx context.Context, wg *sync.WaitGroup, _
...
+	sdkCommon.InitializeSentMetrics(s.lc, dic)
+	return true
+}
+
+func (b *Bootstrap) checkDependencyServiceAvailable(serviceKey string, startupTimer startup.Timer) bool {
+	lc := b.deviceService.lc
+	registry := bootstrapContainer.RegistryFrom(b.deviceService.dic.Get)
+	mode := bootstrapContainer.DevRemoteModeFrom(b.deviceService.dic.Get)
+	clients := bootstrapContainer.ConfigurationFrom(b.deviceService.dic.Get).GetBootstrap().Clients
+	pingUrl := (*clients)[serviceKey].Url() + common.ApiPingRoute
```
Comment (cloudxxx8) [inline pkg/service/init.go:145]:
```suggestion
	clientInfo, ok := (*clients)[serviceKey]
	if !ok {
	  lc.Errorf("Client configuration for '%s' not found, missing common config? Use -cp or -cc flags for common config.", serviceKey)
	}
	pingUrl := clientInfo.Url() + common.ApiPingRoute
```

this function might be copied to other places, so add the check to prevent panic

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Review by cloudxxx8 — APPROVED** [review]
LGTM
