### PR TITLE
fix: Fix cache concurrent read write error

### LINKED ISSUE #1710: Fix cache concurrent map read write error
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device service

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
The cache all() or forName() function returns map and slice reference, and it will cause concurrent map read write error.

## 🔥 Exception or Error
<pre><code>
fatal error: concurrent map read and map write
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by weichou1229**
Since the cache share data, the map and slice should be cloned to prevent concurrent read write error.

Closes #1710

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/device-sdk-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) not impact
  <link to docs PR>

### CODE REVIEW

File: internal/cache/devices.go [hunk 1]
```diff
@@ -92,7 +92,7 @@ func (d *deviceCache) ForName(name string) (models.Device, bool) {
 	if !ok {
 		return models.Device{}, false
 	}
-	return *device, ok
+	return device.Clone(), ok
```
Comment (judehung) [inline internal/cache/devices.go:95]: We can add a comment to remind why we return clone here.
```suggestion
        // As the cache device contains pointer fields(map and slice), directly return device may cause concurrent map read 
	// or write if the invoker spawn another goroutine to manipulate the device, so returning the clone of device here
	return device.Clone(), ok
```

File: internal/cache/profiles.go [hunk 2]
```diff
@@ -67,7 +67,7 @@ func (p *profileCache) ForName(name string) (models.DeviceProfile, bool) {
 	if !ok {
 		return models.DeviceProfile{}, false
 	}
-	return *profile, ok
+	return profile.Clone(), ok
```
Comment (judehung) [inline internal/cache/profiles.go:70]:
```suggestion
        // As the cache profile contains pointer fields(map and slice), directly return profile may cause concurrent map read 
	// or write if the invoker spawn another goroutine to manipulate the profile, so returning the clone of profile here
	return profile.Clone(), ok
```

File: internal/cache/provisionwatcher.go [hunk 3]
```diff
@@ -51,7 +51,7 @@ func (p *provisionWatcherCache) ForName(name string) (models.ProvisionWatcher, b
 	if !ok {
 		return models.ProvisionWatcher{}, false
 	}
-	return *watcher, ok
+	return watcher.Clone(), ok
```
Comment (judehung) [inline internal/cache/provisionwatcher.go:54]:
```suggestion
        // As the cache watcher contains pointer fields(map and slice), directly return watcher may cause concurrent map read 
	// or write if the invoker spawn another goroutine to manipulate the watcher, so returning the clone of watcher here
	return watcher.Clone(), ok
```

File: internal/cache/devices.go (hunk 1 above)
Comment (weichou1229) [reply internal/cache/devices.go:97]: Added the comment.

File: internal/cache/provisionwatcher.go (hunk 3 above)
Comment (weichou1229) [reply internal/cache/provisionwatcher.go:56]: Added the comment.

File: internal/cache/profiles.go (hunk 2 above)
Comment (weichou1229) [reply internal/cache/profiles.go:72]: Added the comment.

**Review by judehung — APPROVED** [review]
LGTM
